version: '3.9'

services:
  backend:
    image: gianlucaflorian/cardtradermanager-backend:latest
    build:
      context: .
      dockerfile: /CardTraderManager.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5050:5050"
    networks:
      - cardtrader-network
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_ENVIRONMENT=Development

  frontend:
    image: gianlucaflorian/cardtradermanager-frontend:latest
    build:
      context: ./CardTraderManager.Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - cardtrader-network

networks:
  cardtrader-network:
    driver: bridge
